# Generated by Django 4.1.5 on 2023-01-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_userbookrelation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrelation',
            name='in_bookmarks',
            field=models.BooleanField(default=False),
        ),
    ]
